spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
         # search-locations: "classpath:/config"
        search-locations: "file:///C://Users//damia//eazybytes//Documents//config"

server:
  port: 8071